### ISSUE TITLE
Unable to do a online installation

### ISSUE THREAD

**Issue by XxRiKxX** [CachyOS/cachyos-calamares#2]
`network installation disabled incorrect configuration` after selecting the desktop env.

**Comment by ptr1337** [comment]
> `network installation disabled incorrect configuration` after selecting the desktop env.

Hi.
Do you have a network connection?
Maybe try to change your DNS to 1.1.1.1

Otherwise try which is mentioned here:
https://forum.cachyos.org/d/55-error-504/17

We have added this "workaround" for the next release. It seems like that github has issues when fetching the file currently from some DNS.

Please try following:
sudo micro /etc/hosts
` 185.199.108.133 raw.githubusercontent.com`

Add this line and then start calamares. Please report if this did help

**Comment by ptr1337** [comment]
We did a testing repo which contains a fix for this. Please try this:
https://mirror.cachyos.org/ISO/testing/

**Comment by ptr1337** [comment]
New ISO has been released with the fix.
Please test if thi9s fixes your issue.
